baseURL = 'https://davidan.dev/'
languageCode = 'en-us'
title = 'David An'
theme = "researcher"
publishDir = "docs"
math = true

[params]
  author = "David An"
  description = "David An - Personal Site" 
  favicon = "favicon.ico"
  googleAnalytics = "G-84P0KS3QHB"
  type = "Website"
  imgpath = "https://davidan.dev/thubmal.jpeg"

[menu]


  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 1

  [[menu.main]]
    name = "News"
    url = "/news"
    weight = 2

  [[menu.main]]
    name = "Readings"
    url = "/readings/all"
    weight = 3
  
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4



[markup.goldmark.parser.attribute]
  block = true
  title = true
[markup.goldmark.renderer]
  unsafe= true