baseURL = 'https://davidzhongtai.com/'
languageCode = 'en-us'
title = 'David An'
theme = "researcher"
publishDir = "docs"
math = true

[menu]


  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 1
  
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 2

  [[menu.main]]
    name = "Nav"
    url = "/sitemap"
    weight = 3
