name = "barks"
description = "A simple, minimalistic theme for personal (or academic) websites."
license = "MIT"
licenselink = "https://github.com/timothygebhard/barks/blob/main/LICENSE"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/timothygebhard/barks/"

# If you have a running demo of the theme.
demosite = "https://timothygebhard.de/projects/barks/"

tags = ["blog", "company"]
features = ["some", "awesome", "features"]

# If the theme has a single author
[author]
    name = "Timothy Gebhard"
    homepage = "https://timothygebhard.de"
